### PR TITLE
fix: tcp updates + initial zmq

### LINKED ISSUE #173: TCP TIME-WAIT
The soak test can exhaust the OS of ephemeral ports. 

Tracking issue to see if we can't get the tcp/server.rs and tcp/client.rs to close in a way that might avoid the socket going into the TIME-WAIT state.

### PR DESCRIPTION
**Pull request by ryanolson**
#### What does the PR do?

- Closes #173 
  - tcp server is responsible for closing the socket
  - tcp client will wait 10s awaiting the server to close the socket after the sentinel has been sent
- adds inital zmq server and client via zmq router and zmq dealer respectively
- adds logging module

Note - I am using `panic!` for an unrecoverable condition. These are conditions that should never happen and should be caught in CI and unit tests.

We should further address these via #171.

soak test can now easily handle 300k tcp open/closes in 1m
```
elapsed: 59.458815336s; count: 330000
test integration::main has been running for over 60 seconds
elapsed: 61.233558603s; count: 340000
```

#### Checklist
- [x] PR title reflects the change and is of format `<commit_type>: <Title>`
- [x] Changes are described in the pull request.
- [ ] Related issues are referenced.
- [ ] Populated [github labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels) field
- [ ] Added [test plan](#test-plan) and verified test passes.
- [ ] Verified that the PR passes existing CI.
- [ ] Verified copyright is correct on all changed files.
- [ ] Added _succinct_ git squash message before merging [ref](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
- [ ] All template sections are filled out.
- [ ] Optional: Additional screenshots for behavior/output changes with before/after.

#### Commit Type:
Check the [conventional commit type](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type)
box here and add the label to the github PR.
- [ ] build
- [ ] ci
- [ ] docs
- [ ] feat
- [x] fix
- [ ] perf
- [ ] refactor
- [ ] revert
- [ ] style
- [ ] test

#### Test plan:

- CI Pipeline ID:

#### Related Issues: (use one of the action keywords Closes / Fixes / Resolves / Relates to)
- closes GitHub issue: #xxx

### CODE REVIEW

File: runtime/rust/src/logging.rs [hunk 1]
```diff
@@ -0,0 +1,292 @@
...
+//!
+//! - Configuration loaded from:
+//!   1. Environment variables (highest priority).
+//!   2. Optional TOML file pointed to by the `TRD_LOGGING_CONFIG_PATH` environment variable.
+//!   3. `/opt/triton/etc/logging.toml`.
+//!
+//! Logging can take two forms: `READABLE` or `JSONL`. The default is `READABLE`. `JSONL`
+//! can be enabled by setting the `TRD_LOGGING_JSONL` environment variable to `1`.
+//!
+//! Filters can be configured using the `TRD_LOG` environment variable or by setting the `filters`
```
Comment (ptarasiewiczNV) [inline runtime/rust/src/logging.rs:26]:
```suggestion
//! Filters can be configured using the `TRD_LOG` environment variable or by setting the `log_filters`
```

**Review by ptarasiewiczNV — APPROVED** [review]
lgtm (from perspective of my very limited rust knowledge)

File: runtime/rust/src/logging.rs [hunk 2]
```diff
@@ -0,0 +1,292 @@
...
+use tracing::{Event, Subscriber};
+use tracing_subscriber::fmt::{format::Writer, FormattedFields};
+use tracing_subscriber::fmt::{FmtContext, FormatFields};
+use tracing_subscriber::prelude::*;
+use tracing_subscriber::registry::LookupSpan;
+use tracing_subscriber::EnvFilter;
+use tracing_subscriber::{filter::Directive, fmt};
+
+/// ENV used to set the log level
+const FILTER_ENV: &str = "TRD_LOG";
```
[the remark this answers is not in the document]
Comment (ryanolson) [reply runtime/rust/src/logging.rs:56]: `TRD_LOG=info` is all you need.

but you can also, 

```
TRD_LOG=triton_distributed=trace,error
```

which lets all trd to trace and third party bits to error

[the remark this answers is not in the document]
Comment (ryanolson) [reply runtime/rust/src/logging.rs:56]: normally it's `RUST_LOG`, but we can change the variable name.

File: runtime/rust/src/pipeline/network/tcp/client.rs [hunk 3]
```diff
@@ -193,46 +220,43 @@ async fn handle_reader(
...
+                                    ControlMessage::Sentinel => {
+                                        // TODO(#171) - address fatal errors
+                                        panic!("received a sentinel message; this should never happen");
                                     }
                                 }
                            }
                            _ => {
-                                // not a control message, so we just continue
-                               continue;
+                               // not a control message, so we just continue
```
[the remark this answers is not in the document]
Comment (ryanolson) [reply runtime/rust/src/pipeline/network/tcp/client.rs]: fixed

File: runtime/rust/src/pipeline/network/tcp/client.rs [hunk 4]
```diff
@@ -134,11 +133,11 @@ impl TcpClient {
             .map_err(|e| error!("failed to send handshake: {:?}", e))?;
 
         // set up the channel to send bytes to the transport layer
-        let (bytes_tx, bytes_rx) = tokio::sync::mpsc::channel(16);
+        let (bytes_tx, bytes_rx) = tokio::sync::mpsc::channel(64);
```
Comment (rmccorm4) [inline runtime/rust/src/pipeline/network/tcp/client.rs:136]: How is this value tuned? When is 64 better than 16? When is 128 > 64? What's the con to increasing it? Should it be configured differently for different scenarios?

File: runtime/rust/src/pipeline/network/tcp/server.rs [hunk 5]
```diff
@@ -461,133 +444,171 @@ async fn tcp_listener(
         }
 
         // we need to know the buffer size from the registration options; add this to the RequestRecvConnection object
-        let (tx, rx) = mpsc::channel(16);
+        let (response_tx, response_rx) = mpsc::channel(64);
```
Comment (rmccorm4) [inline runtime/rust/src/pipeline/network/tcp/server.rs:447]: Same question here

File: runtime/rust/src/transports/zmq.rs [hunk 6]
```diff
@@ -0,0 +1,418 @@
...
+        let context = Context::new();
+        let address = "tcp://127.0.0.1:1337";
+        let token = CancellationToken::new();
+
+        // Start server
+        let (server, handle) = Server::new(&context, address, token.clone()).await?;
+        let state = server.state.clone();
+
+        let id = "test-request".to_string();
+        let (tx, mut rx) = tokio::sync::mpsc::channel(512);
```
Comment (rmccorm4) [inline runtime/rust/src/transports/zmq.rs:378]: Same question here
